name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy docs

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: project_folder   #default is the root of the repository
          REQUIREMENT_PATH: project_folder/requirements.txt  #default is requirement.
      - name: Deploy to GH Pages
          uses: mhausenblas/mkdocs-deploy-gh-pages@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}