# This is a basic workflow to help you get started with Actions

name: Build And Deploy Gh05tVerse mkdoc Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - GithubActions
  pull_request:
    branches:
    - main
    - GitHubActions

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy2.7', 'pypy3.7', 'pypy3.8' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Github Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.workspace }}
        run: echo ${{ github.workspace }}

      # Runs a single command using the runners shell
      - name: Check Current Files & Landing Folder
        run:  ls && pwd

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Runs Commands To Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          echo [ Installing The Python Dependencies ] \n
          pip install mkdocs mkdocs-material
          echo [ Completed Installing Python Dependencies ] \n
 
      # Deploy The mkdocs webstie
      - name: Deploy mkdocs Website
        run: |
          pwd
          cd Gh05tVerse
          git pull
          mkdocs gh-deploy --clean --remote-branch main
          echo [ Completed Deploying The Website ] \n
